const fs=require('fs');
let css=fs.readFileSync('style.css','utf8');
const add=[];
add.push('/* ===== HERO ===== */');
add.push('.hero{position:relative;border-radius:var(--radius-xl);padding:48px 40px;margin-bottom:40px;overflow:hidden;background:linear-gradient(135deg,var(--bg3) 0%,var(--bg4) 100%);border:1px solid rgba(124,106,247,.15)}');
add.push('.hero h1{font-size:2.6rem;font-weight:900;line-height:1.1;margin-bottom:16px;letter-spacing:-1px}');
add.push('.hero h1 span{background:linear-gradient(135deg,var(--accent3) 0%,var(--pink) 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}');
add.push('.hero p{color:var(--text2);font-size:1.05rem;margin-bottom:28px;max-width:520px}');
add.push('.hero-btns{display:flex;gap:12px;flex-wrap:wrap}');
add.push('.hero-btns .btn-primary{width:auto}');
add.push('.hero-stats{display:flex;gap:32px;flex-wrap:wrap;margin-top:40px}');
add.push('.stat span{font-size:2rem;font-weight:900;background:linear-gradient(135deg,var(--accent3),var(--teal));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;display:block}');
add.push('.stat p{color:var(--text2);font-size:.85rem;font-weight:500;margin-top:2px}');
add.push('.featured-section h2{font-size:1.4rem;font-weight:800;margin-bottom:20px}');
add.push('/* ===== BOOKS GRID ===== */');
add.push('.books-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:18px}');
add.push('.book-card{background:var(--bg2);border-radius:var(--radius-lg);overflow:hidden;cursor:pointer;transition:transform .25s,box-shadow .25s;border:1px solid rgba(255,255,255,.04);position:relative}');
add.push('.book-card:hover{transform:translateY(-5px);box-shadow:0 16px 40px rgba(0,0,0,.5),0 0 0 1px rgba(124,106,247,.2)}');
add.push('.book-cover{width:100%;aspect-ratio:2/3;overflow:hidden;position:relative}');
add.push('.book-cover img{width:100%;height:100%;object-fit:cover;transition:transform .3s}');
add.push('.book-card:hover .book-cover img{transform:scale(1.05)}');
add.push('.cover-placeholder{width:100%;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;padding:12px;text-align:center}');
add.push('.cover-placeholder span{font-size:2.5rem}');
add.push('.cover-placeholder p{font-size:.72rem;color:rgba(255,255,255,.75);font-weight:600;line-height:1.3}');
add.push('.book-info{padding:10px 12px 12px}');
add.push('.book-info h4{font-size:.82rem;font-weight:700;margin-bottom:3px;line-height:1.3;color:var(--text)}');
add.push('.book-info p{font-size:.74rem;color:var(--text2)}');
add.push('.book-genre{display:inline-block;margin-top:6px;padding:2px 9px;border-radius:20px;font-size:.67rem;font-weight:600;background:rgba(124,106,247,.15);color:var(--accent3);border:1px solid rgba(124,106,247,.2)}');
add.push('.book-card-actions{position:absolute;top:6px;right:6px;display:flex;flex-direction:column;gap:4px;opacity:0;transition:opacity .2s}');
add.push('.book-card:hover .book-card-actions{opacity:1}');
add.push('.book-action-btn{width:28px;height:28px;border-radius:50%;border:none;cursor:pointer;font-size:.75rem;display:flex;align-items:center;justify-content:center;transition:all .2s;backdrop-filter:blur(8px)}');
add.push('.book-action-btn.fav{background:rgba(244,114,182,.2);color:var(--pink)}');
add.push('.book-action-btn.fav:hover,.book-action-btn.fav.active{background:var(--pink);color:#fff}');
add.push('.book-action-btn.later{background:rgba(45,212,191,.2);color:var(--teal)}');
add.push('.book-action-btn.later:hover,.book-action-btn.later.active{background:var(--teal);color:#000}');
